build:
  environment:
    php:
      version: '8.1'
  dependencies:
    before:
      # Scrutinizer usa Composer 2 di default nelle nuove versioni
      # Se fallisce, il problema è altrove (cache, rete, ecc.)
      - composer --version
    override:
      - composer install --no-interaction --prefer-dist --no-scripts

filter:
  excluded_paths:
    - tests/*
    - vendor/*
    - node_modules/*
    - mcp-server/*
    - externals/*
    - assets/*

tools:
  external_code_coverage:
    timeout: 600
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
  php_cpd:
    enabled: true
  php_loc:
    enabled: true
  php_mess_detector:
    enabled: true
  php_analyzer:
    enabled: true
  sensiolabs_security_checker:
    enabled: true

coding_standards:
  php:
    - { tool: 'phpcs', standard: 'PSR2' }
